import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Barlow_Condensed } from 'next/font/google'
import { Poppins } from 'next/font/google'
import {Space_Grotesk} from 'next/font/google'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-popins",
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
});

const sg = Space_Grotesk({
  variable: "--font-sg",
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
});

const barlow = Barlow_Condensed({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-barlow',
  display: 'swap',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
